# Generated by Django 5.1.3 on 2024-12-28 01:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("album_id", models.AutoField(primary_key=True, serialize=False)),
                ("album_name", models.CharField(max_length=100)),
                ("customer_name", models.CharField(max_length=100)),
                ("cover_photo", models.CharField(max_length=100)),
                ("allow_comment", models.BooleanField()),
                ("allow_download", models.BooleanField()),
                ("nb_of_selected_photo", models.PositiveSmallIntegerField()),
                ("created_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now=True)),
                ("expired_date", models.DateField()),
                ("is_created_by_group", models.BooleanField()),
                ("is_shared", models.BooleanField()),
                ("drive_link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=100)),
                ("type", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_metadata_id", models.CharField(max_length=100)),
                ("image_name", models.CharField(max_length=50)),
                ("created_date", models.DateField(default=django.utils.timezone.now)),
                ("modified_date", models.DateField()),
                ("is_favorite", models.BooleanField(default=False)),
                ("comment", models.CharField(blank=True, max_length=200)),
                ("author", models.CharField(max_length=100)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fotowebapp.album",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("type", models.PositiveSmallIntegerField()),
                ("latest_access", models.DateField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fotowebapp.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareInfo",
            fields=[
                ("share_id", models.AutoField(primary_key=True, serialize=False)),
                ("share_link", models.URLField()),
                ("is_public", models.BooleanField()),
                ("expired_date", models.DateField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fotowebapp.album",
                    ),
                ),
                (
                    "is_shared_with_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fotowebapp.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fotowebapp.user"
            ),
        ),
    ]
